###
GET http://localhost:3001/api/colors

###
POST http://localhost:3001/api/preview HTTP/1.1
Content-Type: application/json

{
    "link": "https://lospec.com/palette-list/bubblegum-16"
}

###
POST http://localhost:3001/api/convert HTTP/1.1
Content-Type: application/json

{
    "name": "test palette",
    "link": "https://lospec.com/palette-list/bubblegum-16"
}